<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrada_stock_vivo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Entrada_stock_vivo_model');
    } 

    /*
     * Listing of entrada_stock_vivo
     */
    function index()
    {
        $data['entrada_stock_vivo'] = $this->Entrada_stock_vivo_model->get_all_entrada_stock_vivo();
        
        $data['_view'] = 'entrada_stock_vivo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new entrada_stock_vivo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('cantidad','Cantidad','required|numeric');
		
		if($this->form_validation->run())     
        {   
            date_default_timezone_set('America/Mexico_City');
            $now = date('d-m-Y H:i:s');
            $params = array(
				'cantidad' => $this->input->post('cantidad'),
				'fecha' => $now,
				'usuario' => $_SESSION['name'],
            );
            
            $entrada_stock_vivo_id = $this->Entrada_stock_vivo_model->add_entrada_stock_vivo($params);
            
            $msg['success'] = true;
            echo json_encode($msg);
        }
        else
        {                      
            $msg['success'] = false;
            echo json_encode($msg);
        }
    }  

    /*
     * Editing a entrada_stock_vivo
     */
    function edit($id)
    {   
        // check if the entrada_stock_vivo exists before trying to edit it
        $data['entrada_stock_vivo'] = $this->Entrada_stock_vivo_model->get_entrada_stock_vivo($id);
        
        if(isset($data['entrada_stock_vivo']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('cantidad','Cantidad','required|numeric');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'cantidad' => $this->input->post('cantidad'),
					'fecha' => $this->input->post('fecha'),
					'usuario' => $this->input->post('usuario'),
                );

                $this->Entrada_stock_vivo_model->update_entrada_stock_vivo($id,$params);            
                redirect('entrada_stock_vivo/index');
            }
            else
            {
                $data['_view'] = 'entrada_stock_vivo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The entrada_stock_vivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting entrada_stock_vivo
     */
    function remove($id)
    {
        $entrada_stock_vivo = $this->Entrada_stock_vivo_model->get_entrada_stock_vivo($id);

        // check if the entrada_stock_vivo exists before trying to delete it
        if(isset($entrada_stock_vivo['id']))
        {
            $this->Entrada_stock_vivo_model->delete_entrada_stock_vivo($id);
            redirect('entrada_stock_vivo/index');
        }
        else
            show_error('The entrada_stock_vivo you are trying to delete does not exist.');
    }
    
}
