<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrada_efectivo_caja extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Entrada_efectivo_caja_model');
    } 



    /*
     * Listing of entrada_efectivo_caja
     */
    function index()
    {
        // $data['entrada_efectivo_caja'] = $this->Entrada_efectivo_caja_model->get_all_entrada_efectivo_caja();
        
        // $data['_view'] = 'entrada_efectivo_caja/index';
        // $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new entrada_efectivo_caja
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('efectivo','Efectivo','numeric|required');
		
		if($this->form_validation->run())     
        {   
            date_default_timezone_set('America/Mexico_City');
            $now = date('d-m-Y H:i:s');

            $params = array(
				'importe' => $this->input->post('efectivo'),
				'fecha' => $now,
				'usuario' => $_SESSION['name'],
            );
            
            $entrada_efectivo_caja_id = $this->Entrada_efectivo_caja_model->add_entrada_efectivo_caja($params);
            redirect('ventas/index');
        }
        else
        {            
            redirect('ventas/index');
        }
    }  

    /*
     * Editing a entrada_efectivo_caja
     */
    function edit($id)
    {   
        // check if the entrada_efectivo_caja exists before trying to edit it
        $data['entrada_efectivo_caja'] = $this->Entrada_efectivo_caja_model->get_entrada_efectivo_caja($id);
        
        if(isset($data['entrada_efectivo_caja']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('efectivo','Efectivo','numeric|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'efectivo' => $this->input->post('efectivo'),
					'fecha' => $this->input->post('fecha'),
					'usuario' => $this->input->post('usuario'),
                );

                $this->Entrada_efectivo_caja_model->update_entrada_efectivo_caja($id,$params);            
                redirect('entrada_efectivo_caja/index');
            }
            else
            {
                $data['_view'] = 'entrada_efectivo_caja/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The entrada_efectivo_caja you are trying to edit does not exist.');
    } 

    /*
     * Deleting entrada_efectivo_caja
     */
    function remove($id)
    {
        $entrada_efectivo_caja = $this->Entrada_efectivo_caja_model->get_entrada_efectivo_caja($id);

        // check if the entrada_efectivo_caja exists before trying to delete it
        if(isset($entrada_efectivo_caja['id']))
        {
            $this->Entrada_efectivo_caja_model->delete_entrada_efectivo_caja($id);
            redirect('entrada_efectivo_caja/index');
        }
        else
            show_error('The entrada_efectivo_caja you are trying to delete does not exist.');
    }
    
}
