<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gastos_diarios extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gastos_diario_model');

        $this->load->model('Entrada_efectivo_caja_model');
            date_default_timezone_set('America/Mexico_City');
            $now = date('d-m-Y');
            $data['entrada'] = $this->Entrada_efectivo_caja_model->getCaja($now);
            //Si aun no se registro la caja inicial del dia
            if (!$data['entrada']) {
                redirect('caja');
            }
    } 

    function vista_index($data){
            $this->load->view('header_view');
            $this->load->view('menu_top_gastos');
            $this->load->view('menu_left_view');
            $this->load->view('gastos_diarios/index',$data);
            $this->load->view('gastos_diarios/footer_view');
            
            $data['page']="gastos";
            $this->load->view('layout/header',$data);
            $this->load->view('gastos_diarios/index',$data);
            $this->load->view('gastos_diarios/footer_view');
    }
    

    function vista_add(){
        $this->load->view('header_view');
        $this->load->view('menu_top_gastos');
        $this->load->view('menu_left_view');
        $this->load->view('gastos_diarios/add');
        $this->load->view('gastos_diarios/footer_view');

        
    }

    function vista_edit($data){
        $this->load->view('header_view');
        $this->load->view('menu_top_gastos');
        $this->load->view('menu_left_view');
        $this->load->view('gastos_diarios/edit',$data);
        $this->load->view('gastos_diarios/footer_view');

        
    }

    /*
     * Listing of gastos_diarios
     */
    function index()
    {
        $data['gastos_diarios'] = $this->Gastos_diario_model->get_all_gastos_diarios();
        
        if ($this->session->userdata('logged_in')) {
            
            $data['page']="gastos";
            $this->load->view('layout/header',$data);
            $this->load->view('gastos_diarios/index',$data);
            $this->load->view('gastos_diarios/footer_view');
        }else{
            $this->load->view('auth/login');
        }

        
    }

    /*
     * Adding a new gastos_diario
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('importe','Importe','required|numeric');
        $this->form_validation->set_rules('descripcion','Descripcion','required');
        
        if($this->form_validation->run())     
        {   
            $params = array(
                'importe' => $this->input->post('importe'),
                'fecha' => $this->input->post('fecha'),
                'usuario' => $this->input->post('usuario'),
                'status' => $this->input->post('status'),
                'descripcion' => $this->input->post('descripcion'),
            );
            
            $gastos_diario_id = $this->Gastos_diario_model->add_gastos_diario($params);
            redirect('gastos_diarios/index');
        }
        else
        {            
            $data['page']="gastos";
            $this->load->view('layout/header',$data);
            $this->load->view('gastos_diarios/add');
            $this->load->view('gastos_diarios/footer_view');
        }
    }

    /*
     * Editing a gastos_diario
     */
    function edit($id)
    {   
        // check if the gastos_diario exists before trying to edit it
        $data['gastos_diario'] = $this->Gastos_diario_model->get_gastos_diario($id);
        
        if(isset($data['gastos_diario']['id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('importe','Importe','required|numeric');
            $this->form_validation->set_rules('descripcion','Descripcion','required');
        
            if($this->form_validation->run())     
            {   
                $params = array(
                    'importe' => $this->input->post('importe'),
                    'fecha' => $this->input->post('fecha'),
                    'usuario' => $this->input->post('usuario'),
                    'status' => $this->input->post('status'),
                    'descripcion' => $this->input->post('descripcion'),
                );

                $this->Gastos_diario_model->update_gastos_diario($id,$params);            
                redirect('gastos_diarios/index');
            }
            else
            {
                $data['page']="gastos";
                $this->load->view('layout/header',$data);
                $this->load->view('gastos_diarios/edit',$data);
                $this->load->view('gastos_diarios/footer_view');
            }
        }
        else
            show_error('The gastos_diario you are trying to edit does not exist.');
    }

    /*
     * Deleting gastos_diario
     */
    function remove($id)
    {
        $gastos_diario = $this->Gastos_diario_model->get_gastos_diario($id);

        // check if the gastos_diario exists before trying to delete it
        if(isset($gastos_diario['id']))
        {
            $this->Gastos_diario_model->delete_gastos_diario($id);
            redirect('gastos_diarios/index');
        }
        else
            show_error('The gastos_diario you are trying to delete does not exist.');
    }
    
}