<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stock_vivo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Stock_vivo_model');
    } 

    function incrementa(){
        $cantidad = $this->input->post('cantidad');
        $id = 1;
        $stock = $this->Stock_vivo_model->get_stock_vivo($id);

        $stock_cantidad = $stock['cantidad'];
        $new_cantidad = floatval($cantidad) + floatval($stock_cantidad);

        $params = array(
            'cantidad' => $new_cantidad,
        );

        $this->Stock_vivo_model->update_stock_vivo($id,$params);

        $stock = $this->Stock_vivo_model->get_stock_vivo($id);
        $msg['success'] = true;
        $msg['pollo'] = $stock;
        echo json_encode($msg);
    }

    function decrementa(){
        $cantidad = $this->input->post('cantidad');
        $id = 1;
        $stock = $this->Stock_vivo_model->get_stock_vivo($id);

        $stock_cantidad = $stock['cantidad'];
        $new_cantidad = floatval($stock_cantidad) - floatval($cantidad);

        $params = array(
            'cantidad' => $new_cantidad,
        );

        $this->Stock_vivo_model->update_stock_vivo($id,$params);

        $stock = $this->Stock_vivo_model->get_stock_vivo($id);
        $msg['success'] = true;
        $msg['pollo'] = $stock;
        echo json_encode($msg);
    }

    /*
     * Listing of stock_vivo
     */
    function index()
    {
        $data['stock_vivo'] = $this->Stock_vivo_model->get_all_stock_vivo();
        
        $data['_view'] = 'stock_vivo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new stock_vivo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'cantidad' => $this->input->post('cantidad'),
            );
            
            $stock_vivo_id = $this->Stock_vivo_model->add_stock_vivo($params);
            redirect('stock_vivo/index');
        }
        else
        {            
            $data['_view'] = 'stock_vivo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a stock_vivo
     */
    function edit($id)
    {   
        // check if the stock_vivo exists before trying to edit it
        $data['stock_vivo'] = $this->Stock_vivo_model->get_stock_vivo($id);
        
        if(isset($data['stock_vivo']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'cantidad' => $this->input->post('cantidad'),
                );

                $this->Stock_vivo_model->update_stock_vivo($id,$params);            
                redirect('stock_vivo/index');
            }
            else
            {
                $data['_view'] = 'stock_vivo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The stock_vivo you are trying to edit does not exist.');
    } 

    /*
     * Deleting stock_vivo
     */
    function remove($id)
    {
        $stock_vivo = $this->Stock_vivo_model->get_stock_vivo($id);

        // check if the stock_vivo exists before trying to delete it
        if(isset($stock_vivo['id']))
        {
            $this->Stock_vivo_model->delete_stock_vivo($id);
            redirect('stock_vivo/index');
        }
        else
            show_error('The stock_vivo you are trying to delete does not exist.');
    }
    
}
