<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Entrada_stock_vivo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get entrada_stock_vivo by id
     */
    function get_entrada_stock_vivo($id)
    {
        return $this->db->get_where('entrada_stock_vivo',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all entrada_stock_vivo
     */
    function get_all_entrada_stock_vivo()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('entrada_stock_vivo')->result_array();
    }
        
    /*
     * function to add new entrada_stock_vivo
     */
    function add_entrada_stock_vivo($params)
    {
        $this->db->insert('entrada_stock_vivo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update entrada_stock_vivo
     */
    function update_entrada_stock_vivo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('entrada_stock_vivo',$params);
    }
    
    /*
     * function to delete entrada_stock_vivo
     */
    function delete_entrada_stock_vivo($id)
    {
        return $this->db->delete('entrada_stock_vivo',array('id'=>$id));
    }
}
