<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gastos_diario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gastos_diario by id
     */
    function get_gastos_diario($id)
    {
        return $this->db->get_where('gastos_diarios',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all gastos_diarios
     */
    function get_all_gastos_diarios()
    {
        date_default_timezone_set('America/Mexico_City');
        $now = date('d-m-Y');
        $this->db->like('fecha', $now);
        $this->db->order_by('id', 'desc');
        return $this->db->get('gastos_diarios')->result_array();
    }
        
    /*
     * function to add new gastos_diario
     */
    function add_gastos_diario($params)
    {
        $this->db->insert('gastos_diarios',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gastos_diario
     */
    function update_gastos_diario($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('gastos_diarios',$params);
    }
    
    /*
     * function to delete gastos_diario
     */
    function delete_gastos_diario($id)
    {
        return $this->db->delete('gastos_diarios',array('id'=>$id));
    }
}