<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stock_procesado_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stock_procesado by id
     */
    function get_stock_procesado($categoria)
    {
        return $this->db->get_where('stock_procesado',array('categoria'=>$categoria))->row_array();
    }
        
    /*
     * Get all stock_procesado
     */
    function get_all_stock_procesado()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('stock_procesado')->result_array();
    }

    function get_stock_procesado_by_category($categoria){
        $this->db->where('categoria',$categoria);
        $this->db->where('status','disponible');
        $this->db->order_by('id', 'desc');
        return $this->db->get('entrada_stock_procesado')->result_array();
    }
       
    function get_stock_procesado_por_codigo($codigo){
        $this->db->where('status','disponible');
        $this->db->where('codigo_interno',$codigo);
        return $this->db->get('entrada_stock_procesado')->result_array();
    }
        
    /*
     * function to add new stock_procesado
     */
    function add_stock_procesado($params)
    {
        $this->db->insert('stock_procesado',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update stock_procesado
     */
    function update_stock_procesado($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('stock_procesado',$params);
    }
    
    /*
     * function to delete stock_procesado
     */
    function delete_stock_procesado($id)
    {
        return $this->db->delete('stock_procesado',array('id'=>$id));
    }
}
