<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Stock_vivo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get stock_vivo by id
     */
    function get_stock_vivo($id)
    {
        return $this->db->get_where('stock_vivo',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all stock_vivo
     */
    function get_all_stock_vivo()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('stock_vivo')->result_array();
    }
        
    /*
     * function to add new stock_vivo
     */
    function add_stock_vivo($params)
    {
        $this->db->insert('stock_vivo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update stock_vivo
     */
    function update_stock_vivo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('stock_vivo',$params);
    }
    
    /*
     * function to delete stock_vivo
     */
    function delete_stock_vivo($id)
    {
        return $this->db->delete('stock_vivo',array('id'=>$id));
    }
}
